import { execFile } from "child_process";
import { promisify } from "util";
import fs from "fs/promises";
import path from "path";
import { prisma } from "@/lib/db/client";
import { sendCommand } from "@/lib/rcon/client";
import { getContainerStatus } from "@/lib/docker/client";
import { getPanelSettings } from "@/lib/panel-settings";

const execFileAsync = promisify(execFile);

/**
 * Backups are stored as `.tar.gz` archives under
 *   <SERVERS_BASE_PATH>/.backups/<serverId>/<timestamp>.tar.gz
 *
 * The archive contains the entire server data folder (including logs).
 * `tar` is used directly: it ships in System32 on Windows 10+, /usr/bin on
 * macOS/Linux, and gives us native streaming with deflate compression.
 */

const SERVERS_BASE_PATH = process.env.SERVERS_BASE_PATH || "./servers";

function getBackupDir(serverId: string): string {
  return path.resolve(SERVERS_BASE_PATH, ".backups", serverId);
}

/** Excluded from every archive — auto-regenerated by Minecraft on next start. */
const EXCLUDE_PATTERNS = [
  "cache",
  "libraries",
  "versions",
  "*.pid",
];

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true });
}

/** Pause world saving and flush before snapshotting. Best-effort. */
async function pauseSaves(serverId: string): Promise<boolean> {
  try {
    const server = await prisma.server.findUnique({ where: { id: serverId } });
    if (!server?.containerId) return false;
    const status = await getContainerStatus(server.containerId);
    if (status !== "running") return false;

    await sendCommand("localhost", server.rconPort, server.rconPassword, "save-off");
    await sendCommand("localhost", server.rconPort, server.rconPassword, "save-all flush");
    return true;
  } catch (e) {
    console.error(`[backups] pauseSaves failed for ${serverId}:`, e);
    return false;
  }
}

async function resumeSaves(serverId: string) {
  try {
    const server = await prisma.server.findUnique({ where: { id: serverId } });
    if (!server?.containerId) return;
    await sendCommand("localhost", server.rconPort, server.rconPassword, "save-on");
  } catch (e) {
    console.error(`[backups] resumeSaves failed for ${serverId}:`, e);
  }
}

export interface CreateBackupOptions {
  type?: "MANUAL" | "AUTO";
  notes?: string;
}

export async function createBackup(serverId: string, opts: CreateBackupOptions = {}) {
  const server = await prisma.server.findUnique({ where: { id: serverId } });
  if (!server) throw new Error("Server not found");

  const backupDir = getBackupDir(serverId);
  await ensureDir(backupDir);

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const fileName = `${timestamp}.tar.gz`;
  const archivePath = path.join(backupDir, fileName);

  // RCON: pause saves
  const wasPaused = await pauseSaves(serverId);

  try {
    // tar -czf <archive> -C <parent> <basename> [--exclude ...]
    const dataParent = path.dirname(server.dataPath);
    const dataBase = path.basename(server.dataPath);

    const args = ["-czf", archivePath, "-C", dataParent];
    for (const pat of EXCLUDE_PATTERNS) {
      args.push(`--exclude=${dataBase}/${pat}`);
    }
    args.push(dataBase);

    await execFileAsync("tar", args, {
      maxBuffer: 50 * 1024 * 1024,
      timeout: 30 * 60 * 1000, // 30 min
    });
  } catch (e) {
    // Clean up partial archive
    await fs.unlink(archivePath).catch(() => {});
    if (wasPaused) await resumeSaves(serverId);
    throw new Error(`Backup failed: ${(e as Error).message}`);
  }

  if (wasPaused) await resumeSaves(serverId);

  const stat = await fs.stat(archivePath);

  return prisma.backup.create({
    data: {
      serverId,
      fileName,
      size: BigInt(stat.size),
      type: opts.type ?? "MANUAL",
      notes: opts.notes ?? null,
    },
  });
}

export async function listBackups(serverId: string) {
  return prisma.backup.findMany({
    where: { serverId },
    orderBy: { createdAt: "desc" },
  });
}

export async function deleteBackup(serverId: string, backupId: string) {
  const backup = await prisma.backup.findUnique({ where: { id: backupId } });
  if (!backup || backup.serverId !== serverId) throw new Error("Backup not found");

  const archivePath = path.join(getBackupDir(serverId), backup.fileName);
  await fs.unlink(archivePath).catch(() => {});
  await prisma.backup.delete({ where: { id: backupId } });
}

export interface RestoreOptions {
  /** If empty/omitted: full restore. Otherwise restore only these top-level paths. */
  paths?: string[];
}

/**
 * Restore a backup. The server MUST be stopped before calling this.
 *
 * Full restore: wipes the data folder (except .backups) and re-extracts.
 * Partial restore: extracts only the listed top-level entries
 *   (e.g. ["world", "world_nether", "world_the_end"] or ["plugins"]).
 */
export async function restoreBackup(serverId: string, backupId: string, opts: RestoreOptions = {}) {
  const server = await prisma.server.findUnique({ where: { id: serverId } });
  if (!server) throw new Error("Server not found");

  const backup = await prisma.backup.findUnique({ where: { id: backupId } });
  if (!backup || backup.serverId !== serverId) throw new Error("Backup not found");

  if (server.containerId) {
    const status = await getContainerStatus(server.containerId);
    if (status === "running") {
      throw new Error("Server must be stopped before restoring");
    }
  }

  const archivePath = path.join(getBackupDir(serverId), backup.fileName);
  await fs.access(archivePath); // throws if missing

  const dataParent = path.dirname(server.dataPath);
  const dataBase = path.basename(server.dataPath);

  if (!opts.paths || opts.paths.length === 0) {
    // Full restore — wipe everything inside data folder except the .backups dir
    const entries = await fs.readdir(server.dataPath);
    for (const e of entries) {
      await fs.rm(path.join(server.dataPath, e), { recursive: true, force: true });
    }

    await execFileAsync("tar", ["-xzf", archivePath, "-C", dataParent], {
      maxBuffer: 50 * 1024 * 1024,
      timeout: 30 * 60 * 1000,
    });
    return;
  }

  // Partial restore — wipe only the targets first, then extract them
  for (const p of opts.paths) {
    if (p.includes("..") || path.isAbsolute(p)) {
      throw new Error(`Invalid restore path: ${p}`);
    }
    await fs.rm(path.join(server.dataPath, p), { recursive: true, force: true });
  }

  // tar entries inside the archive are prefixed with the data folder basename
  const tarPaths = opts.paths.map((p) => `${dataBase}/${p}`);
  await execFileAsync("tar", ["-xzf", archivePath, "-C", dataParent, ...tarPaths], {
    maxBuffer: 50 * 1024 * 1024,
    timeout: 30 * 60 * 1000,
  });
}

/**
 * List the top-level entries inside a backup archive — used by the
 * partial-restore UI to show available worlds/plugins/etc.
 */
export async function inspectBackup(serverId: string, backupId: string) {
  const backup = await prisma.backup.findUnique({ where: { id: backupId } });
  if (!backup || backup.serverId !== serverId) throw new Error("Backup not found");

  const archivePath = path.join(getBackupDir(serverId), backup.fileName);
  const { stdout } = await execFileAsync("tar", ["-tzf", archivePath], {
    maxBuffer: 50 * 1024 * 1024,
  });

  // Lines look like "<dataBase>/world/", "<dataBase>/plugins/foo.jar", etc.
  // Collect unique top-level entries (the segment after the data-folder prefix).
  const top = new Set<string>();
  for (const line of stdout.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const parts = trimmed.split("/");
    if (parts.length >= 2 && parts[1]) top.add(parts[1]);
  }

  return Array.from(top).sort();
}

export async function getBackupArchivePath(serverId: string, backupId: string): Promise<string> {
  const backup = await prisma.backup.findUnique({ where: { id: backupId } });
  if (!backup || backup.serverId !== serverId) throw new Error("Backup not found");
  return path.join(getBackupDir(serverId), backup.fileName);
}

/** Remove backups older than the configured retention window. */
export async function cleanupOldBackups() {
  const settings = await getPanelSettings();
  const cutoff = new Date(Date.now() - settings.backupRetentionDays * 24 * 60 * 60 * 1000);

  const old = await prisma.backup.findMany({
    where: { type: "AUTO", createdAt: { lt: cutoff } },
  });

  for (const b of old) {
    try {
      await fs.unlink(path.join(getBackupDir(b.serverId), b.fileName));
    } catch { /* ignore */ }
    await prisma.backup.delete({ where: { id: b.id } }).catch(() => {});
  }
  return old.length;
}
